#postgres
#pgadmin

# version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: ums_postgres
    restart: on-failure

    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready" ,"-U", "auth"]
      interval: 30s
      timeout: 30s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: ums_pgadmin
    restart: on-failure
    ports:
      - '5050:80'
      - '5051:443'
    environment:
       PGADMIN_DEFAULT_EMAIL: admin@gmail.com
       PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres: